version: '3.3'

services:
    dp-search-data-extractor:
        build:
            context: ../../
            dockerfile: Dockerfile.local
        user: "${MY_UID}:${MY_GID}"
        command:
            - go 
            - test 
            - -cover
            - -race
            - -coverpkg=github.com/ONSdigital/dp-search-data-extractor/... 
            - -component
        volumes:
            - ../../:/dp-search-data-extractor
        depends_on:
            - kafka-1
        ports:
            - "25800:25800"
        environment:
            BIND_ADDR:                          ":25800"
            SERVICE_AUTH_TOKEN:                 "testToken"
            COMPONENT_TEST_USE_LOG_FILE:        "${COMPONENT_TEST_USE_LOG_FILE-false}"
            STOP_CONSUMING_ON_UNHEALTHY:        "true"
            KAFKA_ADDR:                         "kafka-1:9092"
            KAFKA_CONSUMER_MIN_BROKERS_HEALTHY: 1
            KAFKA_PRODUCER_MIN_BROKERS_HEALTHY: 1
            KAFKA_SEC_PROTO:                    ""
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:25800/health" ]
            interval: ${HEALTHCHECK_INTERVAL:-30s}
            timeout: 10s
            retries: 10
