---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.22.4-bullseye

inputs:
  - name: dp-search-data-extractor

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-search-data-extractor/ci/scripts/build.sh
