swagger: "3.0"
info:
  description: ""
  version: "1.0.0"
  title: "Upstream service endpoints"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
schemes:
  - "https"
paths:
  /resource:
    get:
      operationId: GetResources
      summary: "Get Resources Endpoint"
      description: "Endpoint for getting all resources that are wanted to be indexed in search"
      produces:
        - application/json
      parameters:
        - in: query
          name: limit
          description: "The number of resources requested, defaulted to 10 and limited to 1000."
          type: integer
          required: false
          default: 10
        - in: query
          name: offset
          description: >
            The offset into the complete ordered set of resources which satisfy the query, which 
            specifies the first resource to return (starting at 0). Use this parameter as a pagination 
            mechanism along with the limit parameter.
          type: integer
          required: false
          default: 0
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/GetResourceResponse"
        400:
          description: Bad Request
        500:
          description: Internal server error

definitions:
  GetResourcesResponse:
    type: object
    properties:
      count:
        type: integer
        description: How many resources are present in the response
      items: 
        type: array
        description: Array containing results.
        items: 
          oneOf:
            - $ref: './resource_metadata.yml#/components/payloads/StandardPayload'
            - $ref: './resource_metadata.yml#/components/payloads/ReleasePayload'
      limit:
        type: integer
        description: Max number of items we're returning in this response.
      offset:
        type: integer
        description: >
          The number of documents into the full list that this particular response is starting at, 
          this should default to 0 if not set.
      total_count:
        type: integer
        description: How many resources are available in total
